Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza     Obtener la cola (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Obtener la cola
     Failure/Error: aux = @lista.get_tail()

     NoMethodError:
       undefined method `get_tail' for #<Lista:0x000055dc678d3120>
       Did you mean?  get_head
     # ./spec/feeding_spec.rb:152:in `block (3 levels) in <top (required)>'

Finished in 0.00827 seconds (files took 0.15022 seconds to load)
18 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:150 # Lista Probando funcionamiento de la lista doblemente enlazada Obtener la cola