Comparar kcal de alimentos con Comparable     Operador < (FAILED - 1)
Failures:

  1) Lista Comparar kcal de alimentos con Comparable Operador <
     Failure/Error: expect(@carne_vaca < @lentejas).to eq(false)

     NoMethodError:
       undefined method `<' for #<Alimento:0x00005593b5818140>
     # ./spec/feeding_spec.rb:306:in `block (3 levels) in <top (required)>'

Finished in 0.02226 seconds (files took 0.2379 seconds to load)
37 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:305 # Lista Comparar kcal de alimentos con Comparable Operador <