Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza     Obtener la cola     Obtener la tamaño (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Obtener la tamaño
     Failure/Error: expect(@lista.get_size()).to eq(1)

     NoMethodError:
       undefined method `get_size' for #<Lista:0x0000562527b08e50>
       Did you mean?  get_tail
     # ./spec/feeding_spec.rb:158:in `block (3 levels) in <top (required)>'

Finished in 0.00843 seconds (files took 0.15894 seconds to load)
19 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:156 # Lista Probando funcionamiento de la lista doblemente enlazada Obtener la tamaño