Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza     Obtener la cola     Obtener la tamaño     Insertar grupo de alimentos     Mostrar lista (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Mostrar lista
     Failure/Error: expect(@lista.show_list()).to eq("(Carne de cordero, 18.0, 0.0, 17.0, 20.0, 185.0)(Camarones, 17.6, 1.5, 0.6, 18.0, 2.0)(Salmón, 19.9, 0.0, 13.6, 6.0, 3.7)(Lentejas, 23.5, 52.0, 1.4, 0.4, 3.4)")

     NoMethodError:
       undefined method `show_list' for #<Lista:0x000055bbaaf211e0>
     # ./spec/feeding_spec.rb:179:in `block (3 levels) in <top (required)>'

Finished in 0.00872 seconds (files took 0.1954 seconds to load)
21 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:172 # Lista Probando funcionamiento de la lista doblemente enlazada Mostrar lista