Plato   Información del plato     Instanciar un objeto plato     Obtener nombre del plato     Obtener porcentaje de proteínas     Obtener porcentaje de carbohidratos     Obtener porcentaje de lípidos     Obtener número de kcal del plato     Obtener el plato formateado   Jerarquía de clases. Clase Eficiencia energética     Instanciar un objeto Eficiencia     Obtener cantidad de gases anuales generados (FAILED - 1)     Obtener cantidad de gases diarios generados (FAILED - 2)     Obtener uso del terreno anual (FAILED - 3)
Failures:

  1) Plato Jerarquía de clases. Clase Eficiencia energética Obtener cantidad de gases anuales generados
     Failure/Error: expect(@eficiencia.get_gasesA()).to eq(5.04)

     NoMethodError:
       undefined method `get_gasesA' for #<Eficiencia:0x00005565ac950440>
       Did you mean?  get_gramos
     # ./spec/feeding_spec.rb:429:in `block (3 levels) in <top (required)>'

  2) Plato Jerarquía de clases. Clase Eficiencia energética Obtener cantidad de gases diarios generados
     Failure/Error: expect(@eficiencia.get_gasesD()).to eq(0.01)

     NoMethodError:
       undefined method `get_gasesD' for #<Eficiencia:0x00005565ac950440>
       Did you mean?  get_gramos
     # ./spec/feeding_spec.rb:433:in `block (3 levels) in <top (required)>'

  3) Plato Jerarquía de clases. Clase Eficiencia energética Obtener uso del terreno anual
     Failure/Error: expect(@eficiencia.get_terreno()).to eq(16.74)

     NoMethodError:
       undefined method `get_terreno' for #<Eficiencia:0x00005565ac950440>
       Did you mean?  get_prt
     # ./spec/feeding_spec.rb:437:in `block (3 levels) in <top (required)>'

Finished in 0.0333 seconds (files took 0.22764 seconds to load)
60 examples, 3 failures

Failed examples:

rspec ./spec/feeding_spec.rb:428 # Plato Jerarquía de clases. Clase Eficiencia energética Obtener cantidad de gases anuales generados
rspec ./spec/feeding_spec.rb:432 # Plato Jerarquía de clases. Clase Eficiencia energética Obtener cantidad de gases diarios generados
rspec ./spec/feeding_spec.rb:436 # Plato Jerarquía de clases. Clase Eficiencia energética Obtener uso del terreno anual