Alimento   Obtener el nombre   Obtener gramos de proteína (FAILED - 1)
Failures:

  1) Alimento Obtener gramos de proteína
     Failure/Error: expect(@carne_vaca.proteina).to eq(21.1)

     NoMethodError:
       undefined method `proteina' for #<Alimento:0x000055d97fe8f068>
     # ./spec/feeding_spec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 0.0022 seconds (files took 0.12421 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:17 # Alimento Obtener gramos de proteína