Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos   Obtener gramos de lípidos   Obtener kilos de gases de efecto invernadero   Obtener uso del terreno anual en m²   Obtener el alimento formateado (FAILED - 1)
Failures:

  1) Alimento Obtener el alimento formateado
     Failure/Error: expect(@carne_cordero.formato).to eq("Nombre: #{@carne_cordero.name} Proteínas: #{@carne_cordero.proteinas} Carbohidratos: #{@carne_cordero.carbohidratos} Lípidos: #{@carne_cordero.lipidos} GasesEI: #{@carne_cordero.gasesEI} Terreno: #{@carne_cordero.terreno}")

     NoMethodError:
       undefined method `proteinas' for #<Alimento:0x00005599460d6e18>
       Did you mean?  proteina
     # ./spec/feeding_spec.rb:61:in `block (2 levels) in <top (required)>'

Finished in 0.00385 seconds (files took 0.13024 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:58 # Alimento Obtener el alimento formateado