Plato   Información del plato     Instanciar un objeto plato     Obtener nombre del plato     Obtener porcentaje de proteínas     Obtener porcentaje de carbohidratos     Obtener porcentaje de lípidos     Obtener número de kcal del plato (FAILED - 1)     Obtener el plato formateado (FAILED - 2)
Failures:

  1) Plato Información del plato Obtener número de kcal del plato
     Failure/Error: expect(@plato.get_kcal()).to eq(426.9)

     NoMethodError:
       undefined method `get_kcal' for #<Plato:0x000055a5afef8d28>
       Did you mean?  get_lpd
     # ./spec/feeding_spec.rb:402:in `block (3 levels) in <top (required)>'

  2) Plato Información del plato Obtener el plato formateado
     Failure/Error: expect(@plato.to_s()).to eq("(carne y lentejas, (Carne, 21.1, 0.0, 3.1, 50.0, 164.0) (Lentejas, 23.5, 52.0, 1.4, 0.4, 3.4) , (100 100 ))")

       expected: "(carne y lentejas, (Carne, 21.1, 0.0, 3.1, 50.0, 164.0) (Lentejas, 23.5, 52.0, 1.4, 0.4, 3.4) , (100 100 ))"
            got: "#<Plato:0x000055a5afef8d28>"

       (compared using ==)
     # ./spec/feeding_spec.rb:406:in `block (3 levels) in <top (required)>'

Finished in 0.04774 seconds (files took 0.21141 seconds to load)
56 examples, 2 failures

Failed examples:

rspec ./spec/feeding_spec.rb:401 # Plato Información del plato Obtener número de kcal del plato
rspec ./spec/feeding_spec.rb:405 # Plato Información del plato Obtener el plato formateado