Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos   Obtener gramos de lípidos   Obtener kilos de gases de efecto invernadero   Obtener uso del terreno anual en m² (FAILED - 1)
Failures:

  1) Alimento Obtener uso del terreno anual en m²
     Failure/Error: expect(@carne_vaca.terreno).to eq(164.0)

     NoMethodError:
       undefined method `terreno' for #<Alimento:0x0000560b078e1008>
     # ./spec/feeding_spec.rb:51:in `block (2 levels) in <top (required)>'

Finished in 0.00358 seconds (files took 0.13821 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:50 # Alimento Obtener uso del terreno anual en m²