Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Extraer por la cola
     Failure/Error: @lista.extract_tail()

     NoMethodError:
       undefined method `extract_tail' for #<Lista:0x00005614f7986c20>
       Did you mean?  extract_head
     # ./spec/feeding_spec.rb:140:in `block (3 levels) in <top (required)>'

Finished in 0.01016 seconds (files took 0.17444 seconds to load)
16 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:138 # Lista Probando funcionamiento de la lista doblemente enlazada Extraer por la cola