Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Insertar por la cabeza
     Failure/Error: @lista.insert_head(@carne_vaca)

     NoMethodError:
       undefined method `insert_head' for nil:NilClass
     # ./spec/feeding_spec.rb:120:in `block (3 levels) in <top (required)>'

Finished in 0.00776 seconds (files took 0.15957 seconds to load)
13 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:118 # Lista Probando funcionamiento de la lista doblemente enlazada Insertar por la cabeza