Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Obtener la cabeza
     Failure/Error: aux = @lista.get_head()

     NoMethodError:
       undefined method `get_head' for #<Lista:0x000055f498608e38>
       Did you mean?  insert_head
     # ./spec/feeding_spec.rb:146:in `block (3 levels) in <top (required)>'

Finished in 0.01482 seconds (files took 0.15637 seconds to load)
17 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:144 # Lista Probando funcionamiento de la lista doblemente enlazada Obtener la cabeza