Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Extraer por la cabeza
     Failure/Error: @lista.extract_head()

     NoMethodError:
       undefined method `extract_head' for #<Lista:0x000055a6e3660028>
     # ./spec/feeding_spec.rb:134:in `block (3 levels) in <top (required)>'

Finished in 0.00817 seconds (files took 0.15755 seconds to load)
15 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:132 # Lista Probando funcionamiento de la lista doblemente enlazada Extraer por la cabeza