Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos   Obtener gramos de lípidos   Obtener kilos de gases de efecto invernadero   Obtener uso del terreno anual en m²   Obtener el alimento formateado   Obtener las kcal del alimento (FAILED - 1)
Failures:

  1) Alimento Obtener las kcal del alimento
     Failure/Error: expect(@carne_vaca.kcal).to eq(112.3)

     NoMethodError:
       undefined method `kcal' for #<Alimento:0x0000563e33121430>
     # ./spec/feeding_spec.rb:71:in `block (2 levels) in <top (required)>'

Finished in 0.00374 seconds (files took 0.12702 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:70 # Alimento Obtener las kcal del alimento