Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos (FAILED - 1)
Failures:

  1) Alimento Obtener gramos de carbohidratos
     Failure/Error: expect(@carne_vaca.carbohidratos).to eq(0.0)

     NoMethodError:
       undefined method `carbohidratos' for #<Alimento:0x000055a182be7f48>
     # ./spec/feeding_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 0.00319 seconds (files took 0.13442 seconds to load)
3 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:26 # Alimento Obtener gramos de carbohidratos