Alimento   Obtener el nombre (FAILED - 1)
Failures:

  1) Alimento Obtener el nombre
     Failure/Error: expect(@carne_vaca.name).to eq("Carne de vaca")

     NoMethodError:
       undefined method `name' for #<Alimento:0x00005586dae7dd88>
     # ./spec/feeding_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 0.00159 seconds (files took 0.15034 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:10 # Alimento Obtener el nombre