MenuDSL   Práctica 10 - Menú DSL     Declaración de la clase MenuDSL     Platos del menú (FAILED - 1)
Failures:

  1) MenuDSL Práctica 10 - Menú DSL Platos del menú
     Failure/Error: plato "Tequeños", :descripcion => "Tequeños con queso llarena", :precio => 4.5

     NoMethodError:
       undefined method `plato' for #<MenuDSL:0x000055b3f8eab030>
     # ./spec/feeding_spec.rb:877:in `block (4 levels) in <top (required)>'
     # ./lib/feeding/menuDSL.rb:13:in `instance_eval'
     # ./lib/feeding/menuDSL.rb:13:in `initialize'
     # ./spec/feeding_spec.rb:876:in `new'
     # ./spec/feeding_spec.rb:876:in `block (3 levels) in <top (required)>'

Finished in 0.05242 seconds (files took 0.23973 seconds to load)
83 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:875 # MenuDSL Práctica 10 - Menú DSL Platos del menú