Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza     Obtener la cola     Obtener la tamaño     Insertar grupo de alimentos (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Insertar grupo de alimentos
     Failure/Error: @lista.insert_group([@carne_vaca, @carne_cordero, @camarones, @salmon, @lentejas])

     NoMethodError:
       undefined method `insert_group' for #<Lista:0x000055eb761fb028 @head=nil, @tail=nil, @size=0>
       Did you mean?  insert_tail
     # ./spec/feeding_spec.rb:167:in `block (3 levels) in <top (required)>'

Finished in 0.00936 seconds (files took 0.18238 seconds to load)
20 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:161 # Lista Probando funcionamiento de la lista doblemente enlazada Insertar grupo de alimentos