Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza     Obtener la cola     Obtener la tamaño     Insertar grupo de alimentos     Mostrar lista   Dieta Española para hombre     Calcular los gases anuales (FAILED - 1)   Dieta Vasca para mujer     Calcular los gases anuales (FAILED - 2)   Dieta Vegetaria para hombre     Calcular los gases anuales (FAILED - 3)   Dieta Vegetalia para mujer     Calcular los gases anuales (FAILED - 4)   Dieta Carnívora para hombre     Calcular los gases anuales (FAILED - 5)
Failures:

  1) Lista Dieta Española para hombre Calcular los gases anuales
     Failure/Error: expect(@española.gases_anuales(@gramos_esp)).to eq(4.97)

     NoMethodError:
       undefined method `gases_anuales' for nil:NilClass
     # ./spec/feeding_spec.rb:227:in `block (3 levels) in <top (required)>'

  2) Lista Dieta Vasca para mujer Calcular los gases anuales
     Failure/Error: expect(@vasca.gases_anuales(@gramos_vas)).to eq(1.49)

     NoMethodError:
       undefined method `gases_anuales' for nil:NilClass
     # ./spec/feeding_spec.rb:233:in `block (3 levels) in <top (required)>'

  3) Lista Dieta Vegetaria para hombre Calcular los gases anuales
     Failure/Error: expect(@vegetaria.gases_anuales(@gramos_vgr)).to eq(13.17)

     NoMethodError:
       undefined method `gases_anuales' for nil:NilClass
     # ./spec/feeding_spec.rb:239:in `block (3 levels) in <top (required)>'

  4) Lista Dieta Vegetalia para mujer Calcular los gases anuales
     Failure/Error: expect(@vegetalia.gases_anuales(@gramos_vgl)).to eq(0.63)

     NoMethodError:
       undefined method `gases_anuales' for nil:NilClass
     # ./spec/feeding_spec.rb:245:in `block (3 levels) in <top (required)>'

  5) Lista Dieta Carnívora para hombre Calcular los gases anuales
     Failure/Error: expect(@carnivora.gases_anuales(@gramos_car)).to eq(31.77)

     NoMethodError:
       undefined method `gases_anuales' for nil:NilClass
     # ./spec/feeding_spec.rb:251:in `block (3 levels) in <top (required)>'

Finished in 0.01147 seconds (files took 0.15952 seconds to load)
26 examples, 5 failures

Failed examples:

rspec ./spec/feeding_spec.rb:226 # Lista Dieta Española para hombre Calcular los gases anuales
rspec ./spec/feeding_spec.rb:232 # Lista Dieta Vasca para mujer Calcular los gases anuales
rspec ./spec/feeding_spec.rb:238 # Lista Dieta Vegetaria para hombre Calcular los gases anuales
rspec ./spec/feeding_spec.rb:244 # Lista Dieta Vegetalia para mujer Calcular los gases anuales
rspec ./spec/feeding_spec.rb:250 # Lista Dieta Carnívora para hombre Calcular los gases anuales