Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos   Obtener gramos de lípidos   Obtener kilos de gases de efecto invernadero (FAILED - 1)
Failures:

  1) Alimento Obtener kilos de gases de efecto invernadero
     Failure/Error: expect(@carne_vaca.gases).to eq(50.0)

     NoMethodError:
       undefined method `gases' for #<Alimento:0x00005596e4ad7f48>
     # ./spec/feeding_spec.rb:43:in `block (2 levels) in <top (required)>'

Finished in 0.00315 seconds (files took 0.1219 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:42 # Alimento Obtener kilos de gases de efecto invernadero