Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos   Obtener gramos de lípidos   Obtener kilos de gases de efecto invernadero   Obtener uso del terreno anual en m²   Obtener el alimento formateado   Obtener las kcal del alimento   Calcular el impacto ambiental de la dieta recomendada para un varón adulto (54gr proteína)     Obtener impacto ambiental de la dieta (FAILED - 1)
Failures:

  1) Alimento Calcular el impacto ambiental de la dieta recomendada para un varón adulto (54gr proteína) Obtener impacto ambiental de la dieta
     Failure/Error: expect(@carne_de_vaca.impacto(47.4,@carne_de_cordero,55.6, @lentejas,42.6, @tofu,125, @nuez,70).to_s).to eq("[3.77, 19.03]")

     NoMethodError:
       undefined method `impacto' for #<Alimento:0x00005607bb3ba808>
     # ./spec/feeding_spec.rb:86:in `block (3 levels) in <top (required)>'

Finished in 0.00613 seconds (files took 0.13049 seconds to load)
9 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:79 # Alimento Calcular el impacto ambiental de la dieta recomendada para un varón adulto (54gr proteína) Obtener impacto ambiental de la dieta