Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola (FAILED - 1)
Failures:

  1) Lista Probando funcionamiento de la lista doblemente enlazada Insertar por la cola
     Failure/Error: @lista.insert_tail(@carne_vaca)

     NoMethodError:
       undefined method `insert_tail' for #<Lista:0x00005603d4885918 @head=nil, @tail=nil, @size=0>
       Did you mean?  insert_head
     # ./spec/feeding_spec.rb:129:in `block (3 levels) in <top (required)>'

Finished in 0.0129 seconds (files took 0.24035 seconds to load)
14 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:127 # Lista Probando funcionamiento de la lista doblemente enlazada Insertar por la cola