Lista   Probando funcionamiento de la lista doblemente enlazada     Generar nodo con struct     Inicializar lista     Insertar por la cabeza     Insertar por la cola     Extraer por la cabeza     Extraer por la cola     Obtener la cabeza     Obtener la cola     Obtener la tamaño     Insertar grupo de alimentos     Mostrar lista   Dieta Española para hombre     Calcular los gases anuales     Calcular el uso de terreno anual     Calcular los gases diarios (FAILED - 1)   Dieta Vasca para mujer     Calcular los gases anuales     Calcular el uso de terreno anual     Calcular los gases diarios (FAILED - 2)   Dieta Vegetaria para hombre     Calcular los gases anuales     Calcular el uso de terreno anual     Calcular los gases diarios (FAILED - 3)   Dieta Vegetalia para mujer     Calcular los gases anuales     Calcular el uso de terreno anual     Calcular los gases diarios (FAILED - 4)   Dieta Carnívora para hombre     Calcular los gases anuales     Calcular el uso de terreno anual     Calcular los gases diarios (FAILED - 5)
Failures:

  1) Lista Dieta Española para hombre Calcular los gases diarios
     Failure/Error: expect(@española.gases_diarios(@gramos_esp)).to eq(0.014)

     NoMethodError:
       undefined method `gases_diarios' for #<Lista:0x000055dfa3cc3bb0>
       Did you mean?  gases_anuales
     # ./spec/feeding_spec.rb:237:in `block (3 levels) in <top (required)>'

  2) Lista Dieta Vasca para mujer Calcular los gases diarios
     Failure/Error: expect(@vasca.gases_diarios(@gramos_vas)).to eq(0.004)

     NoMethodError:
       undefined method `gases_diarios' for #<Lista:0x000055dfa3cc38e0>
       Did you mean?  gases_anuales
     # ./spec/feeding_spec.rb:251:in `block (3 levels) in <top (required)>'

  3) Lista Dieta Vegetaria para hombre Calcular los gases diarios
     Failure/Error: expect(@vegetaria.gases_diarios(@gramos_vgr)).to eq(0.036)

     NoMethodError:
       undefined method `gases_diarios' for #<Lista:0x000055dfa3cc36b0>
       Did you mean?  gases_anuales
     # ./spec/feeding_spec.rb:266:in `block (3 levels) in <top (required)>'

  4) Lista Dieta Vegetalia para mujer Calcular los gases diarios
     Failure/Error: expect(@vegetalia.gases_diarios(@gramos_vgl)).to eq(0.002)

     NoMethodError:
       undefined method `gases_diarios' for #<Lista:0x000055dfa3cc34d0>
       Did you mean?  gases_anuales
     # ./spec/feeding_spec.rb:280:in `block (3 levels) in <top (required)>'

  5) Lista Dieta Carnívora para hombre Calcular los gases diarios
     Failure/Error: expect(@carnivora.gases_diarios(@gramos_car)).to eq(0.087)

     NoMethodError:
       undefined method `gases_diarios' for #<Lista:0x000055dfa3cc32a0>
       Did you mean?  gases_anuales
     # ./spec/feeding_spec.rb:294:in `block (3 levels) in <top (required)>'

Finished in 0.01682 seconds (files took 0.16411 seconds to load)
36 examples, 5 failures

Failed examples:

rspec ./spec/feeding_spec.rb:236 # Lista Dieta Española para hombre Calcular los gases diarios
rspec ./spec/feeding_spec.rb:250 # Lista Dieta Vasca para mujer Calcular los gases diarios
rspec ./spec/feeding_spec.rb:265 # Lista Dieta Vegetaria para hombre Calcular los gases diarios
rspec ./spec/feeding_spec.rb:279 # Lista Dieta Vegetalia para mujer Calcular los gases diarios
rspec ./spec/feeding_spec.rb:293 # Lista Dieta Carnívora para hombre Calcular los gases diarios