Práctica 10 - Plato DSL     Declaración de la clase PlatoDSL     Alimentos del plato (FAILED - 1)
Failures:

  1) PlatoDSL Práctica 10 - Plato DSL Alimentos del plato
     Failure/Error: alimento "Carne de vaca", :gramos => "100 gr"

     NoMethodError:
       undefined method `alimento' for #<PlatoDSL:0x0000563a042a7ad0>
     # ./spec/feeding_spec.rb:831:in `block (4 levels) in <top (required)>'
     # ./lib/feeding/platoDSL.rb:12:in `instance_eval'
     # ./lib/feeding/platoDSL.rb:12:in `initialize'
     # ./spec/feeding_spec.rb:830:in `new'
     # ./spec/feeding_spec.rb:830:in `block (3 levels) in <top (required)>'

Finished in 0.0668 seconds (files took 0.24379 seconds to load)
80 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:829 # PlatoDSL Práctica 10 - Plato DSL Alimentos del plato