Plato   Información del plato     Instanciar un objeto plato     Obtener nombre del plato (FAILED - 1)     Obtener porcentaje de proteínas (FAILED - 2)     Obtener porcentaje de carbohidratos (FAILED - 3)     Obtener porcentaje de lípidos (FAILED - 4)
Failures:

  1) Plato Información del plato Obtener nombre del plato
     Failure/Error: expect(@plato.get_nombre()).to eq("Carne y lentejas")

     NoMethodError:
       undefined method `get_nombre' for #<Plato:0x000055d86b50d180>
     # ./spec/feeding_spec.rb:386:in `block (3 levels) in <top (required)>'

  2) Plato Información del plato Obtener porcentaje de proteínas
     Failure/Error: expect(@plato.get_prt()).to eq(22.3)

     NoMethodError:
       undefined method `get_prt' for #<Plato:0x000055d86b50d180>
     # ./spec/feeding_spec.rb:390:in `block (3 levels) in <top (required)>'

  3) Plato Información del plato Obtener porcentaje de carbohidratos
     Failure/Error: expect(@plato.get_cbh()).to eq(26)

     NoMethodError:
       undefined method `get_cbh' for #<Plato:0x000055d86b50d180>
     # ./spec/feeding_spec.rb:394:in `block (3 levels) in <top (required)>'

  4) Plato Información del plato Obtener porcentaje de lípidos
     Failure/Error: expect(@plato.get_lpd()).to eq(2.25)

     NoMethodError:
       undefined method `get_lpd' for #<Plato:0x000055d86b50d180>
     # ./spec/feeding_spec.rb:398:in `block (3 levels) in <top (required)>'

Finished in 0.03186 seconds (files took 0.22207 seconds to load)
54 examples, 4 failures

Failed examples:

rspec ./spec/feeding_spec.rb:385 # Plato Información del plato Obtener nombre del plato
rspec ./spec/feeding_spec.rb:389 # Plato Información del plato Obtener porcentaje de proteínas
rspec ./spec/feeding_spec.rb:393 # Plato Información del plato Obtener porcentaje de carbohidratos
rspec ./spec/feeding_spec.rb:397 # Plato Información del plato Obtener porcentaje de lípidos