Alimento   Obtener el nombre   Obtener gramos de proteína   Obtener gramos de carbohidratos   Obtener gramos de lípidos (FAILED - 1)
Failures:

  1) Alimento Obtener gramos de lípidos
     Failure/Error: expect(@carne_vaca.lipidos).to eq(3.1)

     NoMethodError:
       undefined method `lipidos' for #<Alimento:0x00005599a21df3a8>
     # ./spec/feeding_spec.rb:35:in `block (2 levels) in <top (required)>'

Finished in 0.00269 seconds (files took 0.12196 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:34 # Alimento Obtener gramos de lípidos