Calcular la huella nutricional de los platos de un menú dietético     Calcular la huella nutricional (FAILED - 1)
Failures:

  1) Plato Calcular la huella nutricional de los platos de un menú dietético Calcular la huella nutricional
     Failure/Error: expect(@eficienciaLC.hn).to eq(1)

     NoMethodError:
       undefined method `hn' for #<Eficiencia:0x0000559dd6e1c480>
     # ./spec/feeding_spec.rb:803:in `block (3 levels) in <top (required)>'

Finished in 0.03973 seconds (files took 0.20261 seconds to load)
76 examples, 1 failure

Failed examples:

rspec ./spec/feeding_spec.rb:802 # Plato Calcular la huella nutricional de los platos de un menú dietético Calcular la huella nutricional